.Dd $Mdocdate: November 29 2017 $
.Dt ikey 7
.Os

.Sh NAME
.Nm ikey
.Nd Ikey Doherty

.Sh SYNOPSIS
Founder of the Solus distribution.

.Sh DESCRIPTION
.Nm
Ikey founded the Solus operating system in December 2015.

.Sh SEE ALSO
.Xr https://en.wikipedia.org/wiki/Solus_(operating_system)

.Sh AUTHORS
.An Zygmunt Krynicki Aq Mt me@zygoon.pl
